language: node_js
node_js:
  - "0.10"
before_install:
  - git submodule update --init --recursive
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
after_script:
  - npm run coveralls
